global:
  scrape_interval: 15s  # 15초마다 데이터 수집

scrape_configs:
  - job_name: "arxiv-rag-service"
    metrics_path: "/metrics"
    static_configs:
      # docker-compose를 사용할 것이므로 서비스 이름(llm-api)으로 접근
      - targets: ["llm-api:8000"]
